// Static team id -> { name, code } map for places that only have a team id
// (e.g. the admin results grid) and don't load the full team list. `code` is
// the flagcdn slug used by the <Flag> component. Mirrors the API seed.
export const TEAMS: Record<string, { name: string; code: string }> = {
  fra: { name: "France", code: "fr" },
  esp: { name: "Spain", code: "es" },
  eng: { name: "England", code: "gb-eng" },
  por: { name: "Portugal", code: "pt" },
  ned: { name: "Netherlands", code: "nl" },
  bel: { name: "Belgium", code: "be" },
  ger: { name: "Germany", code: "de" },
  cro: { name: "Croatia", code: "hr" },
  sui: { name: "Switzerland", code: "ch" },
  aut: { name: "Austria", code: "at" },
  tur: { name: "Türkiye", code: "tr" },
  nor: { name: "Norway", code: "no" },
  cze: { name: "Czechia", code: "cz" },
  sco: { name: "Scotland", code: "gb-sct" },
  swe: { name: "Sweden", code: "se" },
  bih: { name: "Bosnia & Herz.", code: "ba" },
  arg: { name: "Argentina", code: "ar" },
  bra: { name: "Brazil", code: "br" },
  col: { name: "Colombia", code: "co" },
  uru: { name: "Uruguay", code: "uy" },
  ecu: { name: "Ecuador", code: "ec" },
  par: { name: "Paraguay", code: "py" },
  mex: { name: "Mexico", code: "mx" },
  usa: { name: "United States", code: "us" },
  can: { name: "Canada", code: "ca" },
  pan: { name: "Panama", code: "pa" },
  hai: { name: "Haiti", code: "ht" },
  cur: { name: "Curaçao", code: "cw" },
  mar: { name: "Morocco", code: "ma" },
  sen: { name: "Senegal", code: "sn" },
  egy: { name: "Egypt", code: "eg" },
  alg: { name: "Algeria", code: "dz" },
  civ: { name: "Côte d'Ivoire", code: "ci" },
  tun: { name: "Tunisia", code: "tn" },
  cod: { name: "DR Congo", code: "cd" },
  rsa: { name: "South Africa", code: "za" },
  cpv: { name: "Cape Verde", code: "cv" },
  gha: { name: "Ghana", code: "gh" },
  jpn: { name: "Japan", code: "jp" },
  irn: { name: "Iran", code: "ir" },
  kor: { name: "Korea Republic", code: "kr" },
  aus: { name: "Australia", code: "au" },
  qat: { name: "Qatar", code: "qa" },
  uzb: { name: "Uzbekistan", code: "uz" },
  ksa: { name: "Saudi Arabia", code: "sa" },
  irq: { name: "Iraq", code: "iq" },
  jor: { name: "Jordan", code: "jo" },
  nzl: { name: "New Zealand", code: "nz" },
}
