// Generates packages/api/src/db/seed.sql from the canonical team field.
//
// Source of truth is the original client-side teams.js (window.WC_TEAMS). We read
// it once, evaluate it under a tiny `window` shim, and emit:
//   - 48 teams rows (idempotent: ON CONFLICT(id) DO UPDATE — catalog columns only)
//   - the group round-robin match skeleton (12 groups x 6 = 72), status 'scheduled'
//   - the empty knockout skeleton (R32..Final, null teams), filled in by the admin
//
// Matches use ON CONFLICT(id) DO NOTHING so re-seeding never clobbers entered scores.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
// teams.js source lives next to this script (copied from the original repo).
const src = readFileSync(resolve(here, 'teams.src.js'), 'utf8')
const window = {}
// eslint-disable-next-line no-new-func
new Function('window', src)(window)
const TEAMS = window.WC_TEAMS

const sqlStr = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const sqlNum = (v) => (v === null || v === undefined ? 'NULL' : Number(v))

const lines = []
lines.push('-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.')
lines.push('-- Idempotent: teams upsert catalog columns; matches are inserted once and')
lines.push('-- never clobbered (DO NOTHING), so entered results survive a re-seed.')
lines.push('PRAGMA foreign_keys = ON;')
lines.push('')

// ---- teams ----
const cols = ['id','name','abbr','code','rank','conf','grp','star','host',
  'pop','temp','rain','dogs','age','hgt','light','coffee','hue']
lines.push(`-- 48 teams`)
for (const t of TEAMS) {
  const vals = [
    sqlStr(t.id), sqlStr(t.name), sqlStr(t.abbr), sqlStr(t.code), sqlNum(t.rank),
    sqlStr(t.conf), sqlStr(t.group), sqlStr(t.star), t.host ? 1 : 0,
    sqlNum(t.pop), sqlNum(t.temp), sqlNum(t.rain), sqlNum(t.dogs), sqlNum(t.age),
    sqlNum(t.hgt), sqlNum(t.light), sqlNum(t.coffee), sqlNum(t.hue),
  ]
  lines.push(
    `INSERT INTO teams (${cols.join(',')}) VALUES (${vals.join(',')}) ` +
    `ON CONFLICT(id) DO UPDATE SET ` +
    cols.slice(1).map((c) => `${c}=excluded.${c}`).join(', ') + ';'
  )
}
lines.push('')

// ---- group match skeleton (round-robin within each group) ----
const groupsOf = {}
for (const t of TEAMS) (groupsOf[t.group] ||= []).push(t)
const GROUPS = 'ABCDEFGHIJKL'.split('')
lines.push('-- group-stage round-robin skeleton (72 matches), scores entered by admin.')
lines.push('-- kickoff times follow the canonical 3-matchday schedule so the results feed')
lines.push('-- sorts chronologically. Re-seed updates kickoff only (never clobbers scores).')
// Canonical matchday + slot for each pair (i<j) of the 4 group teams (by rank):
//   MD1: 0v3, 1v2   MD2: 0v2, 1v3   MD3: 0v1, 2v3   → [matchday(0..2), slot(0..1)]
const SCHED = { '0-1': [2, 0], '0-2': [1, 0], '0-3': [0, 0], '1-2': [0, 1], '1-3': [1, 1], '2-3': [2, 1] }
const pad = (x) => String(x).padStart(2, '0')
for (const g of GROUPS) {
  const gt = (groupsOf[g] || []).sort((a, b) => (a.rank || 99) - (b.rank || 99))
  let n = 0
  for (let i = 0; i < gt.length; i++)
    for (let j = i + 1; j < gt.length; j++) {
      n++
      const id = `G-${g}-${n}`
      const [md, slot] = SCHED[`${i}-${j}`]
      const kickoff = `2026-06-${pad(11 + md)}T${pad(15 + slot * 3)}:00:00Z`
      lines.push(
        `INSERT INTO matches (id,stage,grp,home_team_id,away_team_id,kickoff,status) VALUES (` +
        `${sqlStr(id)},'group',${sqlStr(g)},${sqlStr(gt[i].id)},${sqlStr(gt[j].id)},${sqlStr(kickoff)},'scheduled') ` +
        `ON CONFLICT(id) DO UPDATE SET kickoff=excluded.kickoff;`
      )
    }
}
lines.push('')

// ---- knockout skeleton (teams assigned later by admin) ----
lines.push('-- knockout skeleton — teams (and scores) assigned by the admin as the bracket fills')
const KO = [['R32', 16], ['R16', 8], ['QF', 4], ['SF', 2], ['Final', 1]]
for (const [stage, count] of KO) {
  for (let i = 1; i <= count; i++) {
    const id = `${stage}-${i}`
    lines.push(
      `INSERT INTO matches (id,stage,grp,home_team_id,away_team_id,status) VALUES (` +
      `${sqlStr(id)},${sqlStr(stage)},NULL,NULL,NULL,'scheduled') ON CONFLICT(id) DO NOTHING;`
    )
  }
}
lines.push('')

writeFileSync(resolve(here, '../src/db/seed.sql'), lines.join('\n'))
writeFileSync(resolve(here, '../src/db/teams.json'), JSON.stringify(TEAMS, null, 0))
console.log(`seed.sql written: ${TEAMS.length} teams, ${GROUPS.length * 6} group matches, 31 knockout slots`)
